/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataanalyzer.dialog;

import com.arib.toast.Toast;
import java.awt.Dialog;

/**
 *
 * @author aribdhuka
 */
public class NewVitalDialog2 extends javax.swing.JDialog {

    private Vital currVital;
    /**
     * Creates new form NewVitalDialog
     * @param parent which component is this dialog bound to
     * @param newVital the vital to write to
     */
    public NewVitalDialog2(Dialog parent, Vital newVital) {
        super(parent, true); //hold user captive
        initComponents();
        currVital = newVital;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lowValueButtonGroup = new javax.swing.ButtonGroup();
        highValueButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        channelField = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        lowValueActive = new javax.swing.JCheckBox();
        highValueActive = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lowValueField = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        highValueField = new javax.swing.JTextPane();
        lowValueInfoRadioButton = new javax.swing.JRadioButton();
        lowValueWarnRadioButton = new javax.swing.JRadioButton();
        lowValueErrorRadioButton = new javax.swing.JRadioButton();
        highValueInfoRadioButton = new javax.swing.JRadioButton();
        highValueWarnRadioButton = new javax.swing.JRadioButton();
        highValueErrorRadioButton = new javax.swing.JRadioButton();
        applyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(channelField);

        jLabel1.setText("Channel");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel3.setText("High Value Warning");

        lowValueActive.setText("Activate");

        highValueActive.setText("Activate");

        jLabel4.setText("If channel < ");

        jScrollPane3.setViewportView(lowValueField);

        jLabel5.setText("If channel > ");

        jScrollPane4.setViewportView(highValueField);

        lowValueButtonGroup.add(lowValueInfoRadioButton);
        lowValueInfoRadioButton.setText("Inform");

        lowValueButtonGroup.add(lowValueWarnRadioButton);
        lowValueWarnRadioButton.setText("Warn");

        lowValueButtonGroup.add(lowValueErrorRadioButton);
        lowValueErrorRadioButton.setText("Error");

        highValueButtonGroup.add(highValueInfoRadioButton);
        highValueInfoRadioButton.setText("Inform");

        highValueButtonGroup.add(highValueWarnRadioButton);
        highValueWarnRadioButton.setText("Warn");

        highValueButtonGroup.add(highValueErrorRadioButton);
        highValueErrorRadioButton.setText("Error");

        applyButton.setBackground(new java.awt.Color(0, 122, 255));
        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Low Value Warning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(highValueErrorRadioButton)
                            .addComponent(jLabel3)
                            .addComponent(highValueInfoRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lowValueInfoRadioButton)
                            .addComponent(lowValueWarnRadioButton)
                            .addComponent(lowValueErrorRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lowValueActive))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(highValueWarnRadioButton)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(highValueActive)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lowValueInfoRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lowValueWarnRadioButton)
                                    .addComponent(jLabel4)))
                            .addComponent(lowValueActive))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lowValueErrorRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(highValueInfoRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(highValueWarnRadioButton)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(highValueActive))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(highValueErrorRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        //channel
        currVital.setChannel(channelField.getText());
        
        //low value
        if(lowValueField.getText().isEmpty() && lowValueActive.isSelected()) {
            Toast.makeToast(this, "Low value empty and low vital active!", Toast.DURATION_LONG);
            return;
        }
        if(lowValueActive.isSelected()) {
            try{
                currVital.setLowValue(Double.parseDouble(lowValueField.getText()));
            } catch (NumberFormatException e) {
                Toast.makeToast(this, "Couldn't parse low value and low vital active!", ERROR);
                return;
            }
        }
        if(lowValueField.getText().isEmpty() && !lowValueActive.isSelected()) {
            currVital.setLowValue(0);
        }
        
        //highvalue
        if(highValueField.getText().isEmpty() && highValueActive.isSelected()) {
            Toast.makeToast(this, "Low value empty and low vital active!", Toast.DURATION_LONG);
            return;
        }
        if(highValueActive.isSelected()) {
            try{
                currVital.setHighValue(Double.parseDouble(highValueField.getText()));
            } catch (NumberFormatException e) {
                Toast.makeToast(this, "Couldn't parse low value and low vital active!", ERROR);
                return;
            }
        }
        if(highValueField.getText().isEmpty() && !highValueActive.isSelected()) {
            currVital.setHighValue(0);
        }
        
        //low value type
        if(lowValueInfoRadioButton.isSelected()) {
            currVital.setLowType(VitalType.Info);
        } else if(lowValueWarnRadioButton.isSelected()) {
            currVital.setLowType(VitalType.Warn);
        } else if(lowValueErrorRadioButton.isSelected()) {
            currVital.setLowType(VitalType.Error);
        }
        
        //high value type
        if(highValueInfoRadioButton.isSelected()) {
            currVital.setHighType(VitalType.Info);
        } else if(highValueWarnRadioButton.isSelected()) {
            currVital.setHighType(VitalType.Warn);
        } else if(highValueErrorRadioButton.isSelected()) {
            currVital.setHighType(VitalType.Error);
        }
        
        //low active
        if(lowValueActive.isSelected()){
            currVital.setLowActive(true);
        } else {
            currVital.setLowActive(false);
        }
        
        //high active
        if(highValueActive.isSelected()){
            currVital.setHighActive(true);
        } else {
            currVital.setHighActive(false);
        }
        
        this.dispose();
        
    }//GEN-LAST:event_applyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextPane channelField;
    private javax.swing.JCheckBox highValueActive;
    private javax.swing.ButtonGroup highValueButtonGroup;
    private javax.swing.JRadioButton highValueErrorRadioButton;
    private javax.swing.JTextPane highValueField;
    private javax.swing.JRadioButton highValueInfoRadioButton;
    private javax.swing.JRadioButton highValueWarnRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JCheckBox lowValueActive;
    private javax.swing.ButtonGroup lowValueButtonGroup;
    private javax.swing.JRadioButton lowValueErrorRadioButton;
    private javax.swing.JTextPane lowValueField;
    private javax.swing.JRadioButton lowValueInfoRadioButton;
    private javax.swing.JRadioButton lowValueWarnRadioButton;
    // End of variables declaration//GEN-END:variables
}
