/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataanalyzer.lambdamap;

import dataanalyzer.MessageBox;
import dataanalyzer.Referencer;
import dataanalyzer.MessageBox;

/**
 * @author Morgan
 * @author Peter
 * @author Preston
 * @author Dante
 */
public class LambdaMapSettings extends javax.swing.JDialog {

    private static int maxRPM;
    private static double targetAFR;
    private static double acceptedError;
    private static int injectorTimeColorMap;

    /**
     * Creates new form LambdaMapSettings
     */
    public LambdaMapSettings(java.awt.Frame parent, boolean modal, int maxRPM, double targetAFR, double acceptedError, int injectorTimeColorMap) {
        super(parent, modal);
        this.maxRPM = maxRPM;
        this.targetAFR = targetAFR;
        this.acceptedError = acceptedError;
        this.injectorTimeColorMap = injectorTimeColorMap;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maxRPMLabel = new javax.swing.JLabel();
        maxRpmField = new javax.swing.JTextField();
        targetAFRLabel = new javax.swing.JLabel();
        targetAfrField = new javax.swing.JTextField();
        afrErrorLabel = new javax.swing.JLabel();
        afrOffsetField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        injectorTimeLabel = new javax.swing.JLabel();
        injectorTimeComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(260, 340));

        maxRPMLabel.setText("Max RPM");

        maxRpmField.setText(String.valueOf(maxRPM));
        maxRpmField.setToolTipText("Enter the Max RPM setting of the ECU");

        targetAFRLabel.setText("Target AFR");

        targetAfrField.setText(String.valueOf(targetAFR));
        targetAfrField.setToolTipText("Enter the desired AFR value you are looking for");

        afrErrorLabel.setText("Acceptable AFR Error");

        afrOffsetField.setText(String.valueOf(acceptedError));
        afrOffsetField.setToolTipText("Enter the Accepted error for the desired AFR you entered above");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsApplied(evt);
            }
        });

        injectorTimeLabel.setText("Injector Time Color Map");

        injectorTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lambda Average", "Lambda Max", "Lambda Min"}));
        injectorTimeComboBox.setSelectedIndex(injectorTimeColorMap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(injectorTimeLabel)
                    .addComponent(afrErrorLabel)
                    .addComponent(targetAFRLabel)
                    .addComponent(maxRPMLabel)
                    .addComponent(maxRpmField)
                    .addComponent(targetAfrField)
                    .addComponent(afrOffsetField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(applyButton))
                    .addComponent(injectorTimeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(maxRPMLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxRpmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(targetAFRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(targetAfrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(afrErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afrOffsetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(injectorTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(injectorTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(applyButton))
                .addContainerGap())
        );

        maxRpmField.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        close();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void settingsApplied(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsApplied
        //checks for valid data in table settings
        try {
            if (Integer.parseInt(maxRpmField.getText()) < 25) {
                throw new NumberFormatException("Max RPM is less than 25!");
            }
            maxRPM = Integer.parseInt(maxRpmField.getText());
            
            if (Double.parseDouble(targetAfrField.getText()) < 10 || Double.parseDouble(targetAfrField.getText()) > 21) {
                throw new NumberFormatException("Target AFR must be between 10 and 21 (inclusive)!");
            }
            targetAFR = Double.parseDouble(targetAfrField.getText());
            
            acceptedError = Double.parseDouble(afrOffsetField.getText());
            acceptedError = Math.abs(acceptedError);
            
            injectorTimeColorMap = injectorTimeComboBox.getSelectedIndex();
            
            close();
        }
        //displays a message box with an error when exceptions are thrown
        catch (NumberFormatException e) {
            new MessageBox(this, "Error validating your settings." + "\n" + "Please make sure your numbers are correct.\n" + e.getMessage(), true).setVisible(true);
        }
    }//GEN-LAST:event_settingsApplied

    public Referencer<Integer> getMaxRPM() {
        return new Referencer(maxRPM);
    }

    public Referencer<Double> getTargetAFR() {
        return new Referencer(targetAFR);
    }

    public Referencer<Double> getAcceptedError() {
        return new Referencer(acceptedError);
    }
    
    public Referencer<Integer> getInjectorTimeColorMap(){
        return new Referencer(injectorTimeColorMap);
    }
    
    public void close() {
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LambdaMapSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LambdaMapSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LambdaMapSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LambdaMapSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LambdaMapSettings dialog = new LambdaMapSettings(new javax.swing.JFrame(), true, maxRPM, targetAFR, acceptedError, injectorTimeColorMap);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afrErrorLabel;
    private javax.swing.JTextField afrOffsetField;
    private javax.swing.JButton applyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> injectorTimeComboBox;
    private javax.swing.JLabel injectorTimeLabel;
    private javax.swing.JLabel maxRPMLabel;
    private javax.swing.JTextField maxRpmField;
    private javax.swing.JLabel targetAFRLabel;
    private javax.swing.JTextField targetAfrField;
    // End of variables declaration//GEN-END:variables
}
