/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataanalyzer.controlbar;

import dataanalyzer.DataAnalyzer;
import dataanalyzer.DomainMode;
import dataanalyzer.InfiniteProgressPanel;
import dataanalyzer.SizeListener;
import java.util.HashMap;

/**
 *
 * @author aribd
 */
public class ControlBar extends javax.swing.JPanel {
    
    // holds which mode the charts are in
    private DomainMode mode;
    
    DataAnalyzer parent;
    
    private int openedFiles = 0;
    private InfiniteProgressPanel ipp;
    
    /**
     * Creates new form ControlBar
     */
    public ControlBar(DataAnalyzer parent) {
        initComponents();
        this.parent = parent;
        mode = DomainMode.TIME;
        this.parent.getAppParameters().put("domainMode", mode);
        loadingText.setText("");

        parent.getChartManager().addDatasetSizeChangeListener(new SizeListener() {
            @Override
            public void sizeUpdate(int newSize) {
                openedFiles = newSize;
                filesOpenLabel.setText(""+openedFiles);
            }
        });
    }
    
    public DomainMode getMode() {
        return mode;
    }
    
    public void setLoading(boolean isLoading, String text) {
        if (isLoading) {
            ipp = new InfiniteProgressPanel();
            ipp.setSize(20, 20);
            loadingPanel.add(ipp);
            ipp.start();
            loadingText.setText(text);
        } else {
            if(ipp != null) {
                ipp.interrupt();
                ipp = null;
                loadingPanel.removeAll();
            }
            loadingText.setText(text);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        domainSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filesOpenLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        loadingPanel = new javax.swing.JPanel();
        loadingText = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1100, 20));
        setRequestFocusEnabled(false);

        domainSlider.setMaximum(1);
        domainSlider.setValue(0);
        domainSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                domainSliderMouseClicked(evt);
            }
        });

        jLabel1.setText("Distance");

        jLabel2.setText("Time");

        jLabel3.setText("Files Open:");

        filesOpenLabel.setText("0");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        loadingPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        loadingPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        loadingPanel.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout loadingPanelLayout = new javax.swing.GroupLayout(loadingPanel);
        loadingPanel.setLayout(loadingPanelLayout);
        loadingPanelLayout.setHorizontalGroup(
            loadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        loadingPanelLayout.setVerticalGroup(
            loadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        loadingText.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filesOpenLabel)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadingText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 704, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(domainSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(domainSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(filesOpenLabel)
                .addComponent(loadingText))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(loadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void domainSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_domainSliderMouseClicked
        // Toogle domain mode
        if(mode == DomainMode.TIME) {
            domainSlider.setValue(1);
            mode = DomainMode.DISTANCE;
        }
        else {
            domainSlider.setValue(0);
            mode = DomainMode.TIME;
        }
        
        this.parent.getAppParameters().put("domainMode", mode);
        //need to trigger charts to update.
        this.parent.triggerChartDomainUpdate();
    }//GEN-LAST:event_domainSliderMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider domainSlider;
    private javax.swing.JLabel filesOpenLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel loadingPanel;
    private javax.swing.JLabel loadingText;
    // End of variables declaration//GEN-END:variables

}
