/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataanalyzer.controlbar;

import dataanalyzer.ChartManager;

/**
 *
 * @author aribd
 */
public class OpenFilesPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form OpenFilesPanel
     */
    public OpenFilesPanel() {
        initComponents();
        
        ChartManager.addDatasetSizeChangeListener((int newSize) -> {
            System.out.println("dataanalyzer.controlbar.OpenFilesPanel.<init>()");
            countOpenFilesLabel.setText(""+newSize);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openFilesLabel = new javax.swing.JLabel();
        countOpenFilesLabel = new javax.swing.JLabel();

        openFilesLabel.setText("Files Open:");

        countOpenFilesLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(openFilesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countOpenFilesLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openFilesLabel)
                    .addComponent(countOpenFilesLabel)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countOpenFilesLabel;
    private javax.swing.JLabel openFilesLabel;
    // End of variables declaration//GEN-END:variables
}
