/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataanalyzer.controlbar;

import dataanalyzer.CategoricalHashMap;
import dataanalyzer.DataAnalyzer;
import dataanalyzer.Dataset;
import dataanalyzer.dialog.VitalsDialog;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author aribd
 */
public class VitalsPanel extends javax.swing.JPanel {

    private DataAnalyzer da;
    
    /**
     * Creates new form VitalsPanel
     */
    public VitalsPanel() {
        initComponents();
        da = null;
        setupListeners();
    }

    public VitalsPanel(DataAnalyzer da) {
        initComponents();
        this.da = da;
        setupListeners();
    }
    
       private void setupListeners() {
        DataAnalyzer.addFileOpenedListener((Object o) -> {
            setVitals();
        });
    }

    public void setVitals() {
        if(da == null)
            return;
        
        VitalsDialog vd = new VitalsDialog(da, false, da.getChartManager().getMainDataset());
        ArrayList<CategoricalHashMap> maps = new ArrayList<>();
        for (Dataset ds : da.getChartManager().getDatasets()) {
            maps.add(ds.getDataMap());
        }
        String ewis = vd.runVitals(maps);
        vitalsTextDialog.setText(ewis);
        vitalsImageDialog.setText("");
        if(Integer.parseInt(""+ewis.charAt(0)) > 0) {
            vitalsImageDialog.setIcon(rescaleIcon(UIManager.getIcon("OptionPane.errorIcon")));
        } else if(Integer.parseInt(""+ewis.charAt(2)) > 0) {
            vitalsImageDialog.setIcon(rescaleIcon(UIManager.getIcon("OptionPane.warningIcon")));
        } else {
            vitalsImageDialog.setIcon(rescaleIcon(UIManager.getIcon("OptionPane.informationIcon")));
        }
    }
    
    private ImageIcon rescaleIcon(Icon icon) {
        BufferedImage bufferedImage = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB); 
        Graphics2D g = bufferedImage.createGraphics(); 
        icon.paintIcon(null, g, 0, 0); 
        g.dispose(); 
        return new ImageIcon(bufferedImage.getScaledInstance(20, 20, Image.SCALE_SMOOTH));
    }

    public void setDataAnalyzer(DataAnalyzer da) {
        this.da = da;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vitalsImageDialog = new javax.swing.JLabel();
        vitalsTextDialog = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 20));
        setMinimumSize(new java.awt.Dimension(0, 20));

        vitalsImageDialog.setText("I");
        vitalsImageDialog.setMaximumSize(new java.awt.Dimension(20, 20));
        vitalsImageDialog.setMinimumSize(new java.awt.Dimension(10, 10));
        vitalsImageDialog.setPreferredSize(new java.awt.Dimension(20, 20));
        vitalsImageDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vitalsImageDialogMouseClicked(evt);
            }
        });

        vitalsTextDialog.setText("0E0W0I");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vitalsImageDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vitalsTextDialog))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vitalsImageDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vitalsTextDialog))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vitalsImageDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vitalsImageDialogMouseClicked
        //launch VitalsDialog
        if(da.getChartManager().getMainDataset() != null) {
            VitalsDialog vd = new VitalsDialog(da, true, da.getChartManager().getMainDataset());
            vd.setVisible(true);
        }

    }//GEN-LAST:event_vitalsImageDialogMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel vitalsImageDialog;
    private javax.swing.JLabel vitalsTextDialog;
    // End of variables declaration//GEN-END:variables
}
