/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataanalyzer;

import javax.swing.Box;

/**
 *
 * @author Peter Glass
 */
public class GPSGraphInternalFrame extends javax.swing.JInternalFrame {
    //class variables
    CategoricalHashMap dataMap;
    DataAnalyzer dataAnalyzer;
    boolean hasData;
    
    /**
     * Creates new form GPSGraphInternalFrame
     * 
     * @param dataAnalyzer current DataAnalyzer frame
     */
    public GPSGraphInternalFrame(DataAnalyzer dataAnalyzer) {
        //sets class variables
        this.hasData = false;
        this.dataAnalyzer = dataAnalyzer;
        
        //sets the content panel of the frame to a GPSGraphPanel
        this.setContentPane(new GPSGraphPanel());
        
        //initializes GPSGraphInternalFrame
        initComponents();
    }
    
    /**
     * Creates new form GPSGraphFrame with a DataAnalyzer frame
     *
     * @param dataAnalyzer current DataAnalyzer frame
     * @param dataMap log data for the car's ECU stored in a CategoricalHashMap
     */
    public GPSGraphInternalFrame(DataAnalyzer dataAnalyzer, CategoricalHashMap dataMap) {
        //sets class variables
        this.dataAnalyzer = dataAnalyzer;
        this.hasData = true;
        this.dataMap = dataMap;
        
        //sets the content panel of the frame to a GPSGraphPanel
        this.setContentPane(new GPSGraphPanel(dataMap));
        
        //initializes GPSGraphInternalFrame
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        popOutMenu = new javax.swing.JMenu();
        overlayJMenuItem = new javax.swing.JMenu();
        speedOverlayJMenuItem = new javax.swing.JMenuItem();
        noOverlayJMenuItem = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(280, 250));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        popOutMenu.setText("  Pop-Out  ");
        jMenuBar.add(Box.createHorizontalGlue());
        popOutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popOutMenuMouseClicked(evt);
            }
        });
        jMenuBar.add(popOutMenu);

        overlayJMenuItem.setText("Overlay");

        speedOverlayJMenuItem.setText("Speed");
        speedOverlayJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedOverlayJMenuItemActionPerformed(evt);
            }
        });
        overlayJMenuItem.add(speedOverlayJMenuItem);

        noOverlayJMenuItem.setText("None");
        noOverlayJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOverlayJMenuItemActionPerformed(evt);
            }
        });
        overlayJMenuItem.add(noOverlayJMenuItem);

        jMenuBar.add(overlayJMenuItem);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popOutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popOutMenuMouseClicked
        //calls the correct constructor based on wheather data has been loaded
        if(hasData){
            new GPSGraphFrame(dataAnalyzer, dataMap).setVisible(true);
        } else {
            new GPSGraphFrame(dataAnalyzer).setVisible(true);
        }
        
        //closes the internal frame, so that the frame can replace it
        dispose();
    }//GEN-LAST:event_popOutMenuMouseClicked

    private void speedOverlayJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedOverlayJMenuItemActionPerformed
        this.setContentPane(new GPSGraphPanel(dataMap, "Time,Speed"));
    }//GEN-LAST:event_speedOverlayJMenuItemActionPerformed

    private void noOverlayJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOverlayJMenuItemActionPerformed
        this.setContentPane(new GPSGraphPanel(dataMap));
    }//GEN-LAST:event_noOverlayJMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem noOverlayJMenuItem;
    private javax.swing.JMenu overlayJMenuItem;
    private javax.swing.JMenu popOutMenu;
    private javax.swing.JMenuItem speedOverlayJMenuItem;
    // End of variables declaration//GEN-END:variables
}
