/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataanalyzer;

import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.JInternalFrame;

/**
 * 
 * @author Peter Glass
 * @author Preston Baxter
 */
public class GPSGraphFrame extends javax.swing.JFrame {
    //class variables
    CategoricalHashMap dataMap;
    DataAnalyzer dataAnalyzer;
    boolean hasData;
    
    /**
     * Creates new form GPSGraphFrame
     */
    public GPSGraphFrame() {
        //initializes GPSGraphFrame
        initComponents();
        
        //sets the content panel of the frame to a GPSGraphPanel
        this.setContentPane(new GPSGraphPanel());
        
        //Disables pop-in buttom when frame is ran independently
        popInMenu.setEnabled(false);
    }
    
    /**
     * Creates new form GPSGraphFrame with a DataAnalyzer frame
     *
     * @param dataAnalyzer current DataAnalyzer frame
     */
    public GPSGraphFrame(DataAnalyzer dataAnalyzer) {
        //initializes GPSGraphFrame
        initComponents();
        
        //sets class variables
        this.dataAnalyzer = dataAnalyzer;
        this.hasData = false;
        
        //sets the content panel of the frame to a GPSGraphPanel
        this.setContentPane(new GPSGraphPanel());
    }
    
    /**
     * Creates new form GPSGraphFrame with a DataAnalyzer frame
     *
     * @param dataAnalyzer current DataAnalyzer frame
     * @param dataMap log data for the car's ECU stored in a CategoricalHashMap
     */
    public GPSGraphFrame(DataAnalyzer dataAnalyzer, CategoricalHashMap dataMap) {
        //initializes GPSGraphFrame
        initComponents();
        
        //sets class variables
        this.dataAnalyzer = dataAnalyzer;
        this.hasData = true;
        this.dataMap = dataMap;
        
        //sets the content panel of the frame to a GPSGraphPanel
        this.setContentPane(new GPSGraphPanel(dataMap));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        popInMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(375, 300));

        popInMenu.setText("  Pop-In  ");
        jMenuBar.add(Box.createHorizontalGlue());
        popInMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popInMenuMouseClicked(evt);
            }
        });
        jMenuBar.add(popInMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popInMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popInMenuMouseClicked
        JInternalFrame TrackMapInternalFrame;
        
        //calls the correct constructor based on wheather data has been loaded
        if(hasData){
            TrackMapInternalFrame = new GPSGraphInternalFrame(dataAnalyzer, dataMap);
        } else {
            TrackMapInternalFrame = new GPSGraphInternalFrame(dataAnalyzer);
        }
        TrackMapInternalFrame.setVisible(true);
        
        //adds the trackMapInternalFrame to a list, to keep track of them
        dataAnalyzer.getTrackMap().add(TrackMapInternalFrame);
        
        //sets the location and size of the trackMapInternalFrame
        Dimension frameSize = dataAnalyzer.getSize();
        TrackMapInternalFrame.setLocation((frameSize.width/4)*3, 0);
        TrackMapInternalFrame.setSize((frameSize.width/4)-18, frameSize.height/2);
        
        //adds the trackMapInternalFrame to the DataAnalyzer frame
        dataAnalyzer.getContentPane().add(TrackMapInternalFrame);
        
        //closes the frame, so that the internal frame can replace it
        dispose();
    }//GEN-LAST:event_popInMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPSGraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPSGraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPSGraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPSGraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPSGraphFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu popInMenu;
    // End of variables declaration//GEN-END:variables
}
